### ISSUE TITLE
Resource list does not populate when using 'All Resource Groups' option

### ISSUE THREAD

**Issue by AErmie** [prchanda/MonDiag#2] opened 2018-10-10 19:18 UTC
After authenticating to an Azure account, the Control Panel section does not populate the Resource list.

**Reproduction steps**

1. Launch the MonDiag tool, and authenticate with an account that has an Azure subscription
2. Select an appropriate Subscription ID
3. Leave the Resource Group selection as 'All Resource Groups'
4. The 'Resource' list is disabled and does not populate

![mondiag-issue01](https://user-images.githubusercontent.com/10376796/46760264-9961f400-cc9f-11e8-8602-dc296315fca9.PNG)

**Comment by prchanda** [comment] 2018-10-11 19:26
Thanks @AErmie for the feedback.. The issue is fixed now, you can download the latest release (2.1.0)...

**Closed as completed by prchanda** 2018-10-11 19:26 UTC
